<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2c4c873d-11b2-467a-beb1-953b47754d13</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.1" />
    <PackageReference Include="Mapster" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
    <Folder Include="Controllers\V2\" />
    <Folder Include="Mapping\" />
    <Folder Include="Models\Dtos\Responses\" />
  </ItemGroup>

</Project>
